### ISSUE TITLE
Assertion failed: all views should be cleaned up on reset

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#115]
We thought [this](https://github.com/phetsims/build-a-nucleus/commit/1f9c894e77ca19451042cc15dd5c84520cad9a17) might have fixed this assertion. But we only have CT up to wedesday evening so maybe a later commit brought up this assertion.
```
build-a-nucleus : fuzz : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691075496267%22%2C%22timestamp%22%3A1691075740183%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: Did not find matching ParticleView for type electron and id 201
Error: Assertion failed: Did not find matching ParticleView for type electron and id 201
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:810:14)
at findParticleView (BANScreenView.ts:718:30)
at animateAndRemoveParticle (BANScreenView.ts:973:11)
at onChangeComplete (ParticleAtom.ts:645:58)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (Animation.ts:321:25)
at listener (TinyEmitter.ts:122:8)
at emit (Sim.ts:413:16)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1691075496267%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691075496267%22%2C%22timestamp%22%3A1691075740183%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1691075496267%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691075496267%22%2C%22timestamp%22%3A1691075740183%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691075496267%22%2C%22timestamp%22%3A1691075740183%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] 0.16666666666666666
[CONSOLE] Assertion failed: Did not find matching ParticleView for type electron and id 201
[PAGE ERROR] Error: Error: Assertion failed: Did not find matching ParticleView for type electron and id 201
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/assert/js/assert.js:28:13)
at DecayScreenView.findParticleView (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:650:15)
at DecayScreenView.animateAndRemoveParticle (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:570:31)
at http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:787:12
at http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/shred/js/model/ParticleAtom.js:518:58
at TinyEmitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at Emitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/axon/js/Emitter.js:50:22)
at Animation.step (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/twixt/js/Animation.js:279:26)
at Timer.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at http://128.138.93.172//continuous-testing/ct-snapshots/1691075496267/chipper/dist/js/joist/js/Sim.js:335:17
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/3/2023, 9:11:36 AM
```

**Comment by zepumph** [comment]
This is blocking memory testing in the [Self Code Review](https://github.com/phetsims/build-a-nucleus/issues/112), raising priority.

**Comment by zepumph** [comment]
Not a ton of progress here today, but I did spend a fair bit of time. I mostly just added assertions in place to try to narrow down what is happening. The errors I'm seeing are all based around something with `changeNucleonType` which may not be doing some important cleanup or something. I found that once at the end of reset, a Particle of type proton was still totally gray, not disposed, and had a particleView still in the map. Quite suspicious if you ask me!

I'll get back to this next time.

**Comment by Luisav1** [comment]
@zepumph and I think is fixed since it didn't come up on CT again. Closing.

**Comment by zepumph** [comment]
I renamed this, because the assertion that is now happening on ct (quite rarely btw) is from an upstream assertion that we added above:

```

build-a-nucleus : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692775910755%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: all views should be cleaned up on reset
Error: Assertion failed: all views should be cleaned up on reset
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:170:18)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692754059845%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692775910755%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692754059845%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692775910755%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692775910755%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 275474
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: all views should be cleaned up on reset
[PAGE ERROR] Error: Error: Assertion failed: all views should be cleaned up on reset
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/assert/js/assert.js:28:13)
at listener (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:123:19)
at TinyEmitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at Emitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:134:23)
at downPropertyObserver (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:79:16)
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at BooleanProperty._notifyListeners (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at BooleanProperty.unguardedSet (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at BooleanProperty.set (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: Cannot fire when already firing
[PAGE ERROR] Error: Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/assert/js/assert.js:28:13)
at PushButtonModel.fire (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:132:15)
at downPropertyObserver (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:79:16)
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at BooleanProperty._notifyListeners (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at BooleanProperty.unguardedSet (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at BooleanProperty.set (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at BooleanProperty.set (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/Property.js:58:11)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/ButtonModel.js:133:25
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/22/2023, 7:27:39 PM

----------------------------------

build-a-nucleus : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692781174662%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: The above cases should cover all possibilities
Error: Assertion failed: The above cases should cover all possibilities
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:345:16)
at returnParticleToStack (NucleonArrowButtons.ts:245:9)
at decreaseNucleonNumberListener (NucleonArrowButtons.ts:130:19)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:315:22)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692754059845%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692781174662%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692754059845%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692781174662%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692754059845%22%2C%22timestamp%22%3A1692781174662%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 837129
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: The above cases should cover all possibilities
[PAGE ERROR] Error: Error: Assertion failed: The above cases should cover all possibilities
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/assert/js/assert.js:28:13)
at ChartIntroScreenView.returnParticleToStack (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:271:17)
at NucleonArrowButtons.decreaseNucleonNumberListener (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/build-a-nucleus/js/common/view/NucleonArrowButtons.js:192:10)
at merge.leftArrowFill (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/build-a-nucleus/js/common/view/NucleonArrowButtons.js:86:165)
at TinyEmitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at Emitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:134:23)
at downPropertyObserver (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/sun/js/buttons/PushButtonModel.js:79:16)
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at BooleanProperty._notifyListeners (http://128.138.93.172//continuous-testing/ct-snapshots/1692754059845/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/22/2023, 7:27:39 PM
```

**Comment by zepumph** [comment]
Ok. I fuzzed for ~30 minutes and could get this error once again. It occurred in the exact same way. It was a "proton" particle (not disposed), with a view still in the view map, and the color was grey. This means that `ParticleAtom.changeNucleonType()` is somehow "losing" our particle in certain circumstances. The best I could come up with is when we swap lists, first we remove and then we add. Perhaps we should make sure that we add first before removing. 

We'll see how it goes tonight on CT.

**Comment by zepumph** [comment]
I'm still seeing the trouble, I added some data to the assertion message, and will keep working on it.

**Comment by zepumph** [comment]
CT has now been clear for the last 3 hours. I'm feeling very optimistic that we fixed this by toggling inputEnabled on the changing nucleon. I'll check back in the morning.

**Comment by zepumph** [comment]
> CT has now been clear for the last 3 hours. I'm feeling very optimistic that we fixed this by toggling inputEnabled on the changing nucleon. I'll check back in the morning.

This did not fix this bug.


Next, I was REALLY hopeful that the bug fixed in #190 would also solve this, but checking back after a weekend of testing, no such luck:


<details>

```
build-a-nucleus : fuzz : unbuilt : query-parameters
http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1694886615486%22%2C%22timestamp%22%3A1694942489923%7D&brand=phet&ea&fuzz&decayScreenProtons=89&decayScreenNeutrons=114&chartIntoScreenProtons=7&chartIntoScreenNeutrons=9
Query: brand=phet&ea&fuzz&decayScreenProtons=89&decayScreenNeutrons=114&chartIntoScreenProtons=7&chartIntoScreenNeutrons=9
Uncaught Error: Assertion failed: all views should be cleaned up on reset
197, proton, disposed:false, Color[r:128 g:128 b:128 a:1]
Error: Assertion failed: all views should be cleaned up on reset
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:124:8)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:61:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1694886615486%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D89%26decayScreenNeutrons%3D114%26chartIntoScreenProtons%3D7%26chartIntoScreenNeutrons%3D9&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1694886615486%22%2C%22timestamp%22%3A1694942489923%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1694886615486%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D89%26decayScreenNeutrons%3D114%26chartIntoScreenProtons%3D7%26chartIntoScreenNeutrons%3D9&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1694886615486%22%2C%22timestamp%22%3A1694942489923%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1694886615486%22%2C%22timestamp%22%3A1694942489923%7D&brand=phet&ea&fuzz&decayScreenProtons=89&decayScreenNeutrons=114&chartIntoScreenProtons=7&chartIntoScreenNeutrons=9
[CONSOLE] enabling assert
[CONSOLE] A nuclide with 89 protons and 114 neutrons does not exist
[CONSOLE] A nuclide with 89 protons and 114 neutrons does not exist
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: all views should be cleaned up on reset
197, proton, disposed:false, Color[r:128 g:128 b:128 a:1]
[PAGE ERROR] Error: Error: Assertion failed: all views should be cleaned up on reset
197, proton, disposed:false, Color[r:128 g:128 b:128 a:1]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/assert/js/assert.js:28:13)
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:74:219)
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/sun/js/buttons/PushButtonModel.js:134:23)
at downPropertyObserver (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/sun/js/buttons/PushButtonModel.js:79:16)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at BooleanProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at BooleanProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1694886615486/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 9/16/2023, 11:50:15 AM

**Comment by samreid** [comment]
@zepumph and @Luisav1 were looking into this. This is a difficult problem which only appears once in every 20-50 columns or so. It seems to be related to the 2nd screen when the mini particle view at the top has a proton change to a neutron (on decay). That is controlled by an animation.  We discussed the following ideas and possibilities:

* Change the assertion in BANScreenView.ResetAllButton.reset from an assertion to an additional "clearing" step. This could be done if we feel this symptom is not indicative of a deeper underlying model problem or symptom that could appear in front of users. I feel this option should be carefully evaluated and ruled out.
* We could hypothesize that animations are responsible for this issue, and transform the relevant animations into "immediate, synchronous" actions, and see if the problem recurs on CT.
* We could hypothesize that the `miniParticleAtom` being connected and disconnected may be related to the problem. For instance, if the miniParticleAtom is connected, and a particle is added, then it is disconnected and then clear doesn't know to visit it and remove particles (it does not appear this is happening in the code, but may be something related).  To that end, we could add the following kinds of instrumentation to get better information about the problem on CT:
  * Trace the state of the particle that has the view remaining. Is it in the miniParticleAtom?
  * Does the problem occur when the miniParticleAtom is connected or disconnected?
  * Trace the times where the mini particle atom is connected and disconnected. On the assertion error, output the last N connects and disconnects and see if they seem to be related to the assertion error.
* Look into other model data structures that may be holding on to the particles without getting cleared.

**Comment by zepumph** [comment]
I feel like we didn't change anything except for unrelated items (animation speed and touch offset) and https://github.com/phetsims/build-a-nucleus/issues/190. But CT has been clear since 9/21 (4 days ago). We may just be ready to close this issue.

**Comment by zepumph** [comment]
@Luisav1 and I haven't seen this on CT in many days, and so are ready to convert this from an assertion to a cleanup step, just in case we hit the need in the wild and don't want a memory leak. Closing

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by pixelzoom** [comment]
Reopened because of https://github.com/phetsims/perennial/issues/468.
